config/routes.rb
TweetDepository::Application.routes.draw do
  root to: "statuses#index"
  match"/:month", to: "statuses#index", as: :statuses_for_month, constraints: { month: /\d{4}-\d{2}/ }
  match "/search", to: "statuses#search", as: :search
  match "auth/:provider/callback", to: "sessions#create"
  resource :sessions, only: [ :destroy ]
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  def index
    if user
      @oldest = user.statuses.oldest
      @newest = user.statuses.newest

      @statuses = user.statuses.order_by_sid
      @cache_name = ["statuses", "recent"]

      if params[:month]
        begin
          @date = Date.strptime("#{params[:month]}-01", "%Y-%m-%d")
          @statuses = @statuses.where("tweeted_at >= ? AND tweeted_at <= ?", @date.beginning_of_month, @date.end_of_month)
          @cache_name = ["statuses", @date.strftime("%Y-%m")]
        rescue ArgumentError => e
        end
      end

      unless @date
        @statuses = @statuses.limit(50)
      end
    else
      render template: "statuses/unauthenticated"
    end
  end

  def search
    if user && params[:q]
      @oldest = user.statuses.oldest
      @newest = user.statuses.newest
    
      @statuses = user.statuses.search(params[:q])
      @statuses = @statuses.limit(500) unless params[:bypass_limit]
      render template: "statuses/index"
    else
      redirect_to root_path
    end
  end

  private

  def user
    @user ||= if public_timeline? && User.exists?
      User.first
    elsif current_user
      current_user
    end
  end
end

app/helpers/statuses_helper.rb
module StatusesHelper
  include Twitter::Autolink

  # Skip the t.co redirect if possible
  def link_to_text(entity, text, href, attributes = {}, options = {})
    href = entity[:expanded_url] if entity[:expanded_url]
    super(entity, text, href, attributes, options)
  end

  def format_status_text(status)
    text, entities = if status.is_retweet? && status.raw_hash[:retweeted_status]
      [status.raw_hash[:retweeted_status][:text], status.raw_hash[:retweeted_status][:entities]]
    elsif status.raw_hash[:entities].present?
      [status.text, status.raw_hash[:entities]]
    else
      [status.text, nil]
    end

    if entities
      auto_link_with_json(text, entities, { username_include_symbol: true, url_class: "autolinked" }).html_safe
    else
      auto_link(text, { username_include_symbol: true, url_class: "autolinked" }).html_safe
    end
  end

  def tweet_dates(oldest, newest)
    date_range = []

    ( (oldest.tweeted_at.to_date)..(newest.tweeted_at.to_date) ).each do |day|
      date_range << day.beginning_of_month
    end

    date_range.uniq!

    date_range = date_range.group_by { |date| date.strftime("%Y") }

    date_range.each_key do |key|
      date_range[key] = date_range[key].reverse
    end

    Hash[date_range.sort.reverse]
  end
end

app/views/statuses/_status.html.haml
- cache status do
  
  %blockquote{ class: (status.is_retweet? ? "retweet" : "tweet") }
    = format_status_text(status)

  %small
    .avatar
      = image_tag "grey.gif", alt: status.screen_name, :"data-original" => status.avatar_url, :class => "lazy"
      %noscript
        = image_tag status.avatar_url, alt: status.screen_name
    - if status.is_retweet?
      Retweeted
      = link_to "@#{status.screen_name}", status.twitter_user_url
    - elsif status.is_reply?
      Replied
    - else
      Tweeted
    = link_to status.twitter_url do
      %time.ago{ datetime: status.tweeted_at.iso8601 }
        = l(status.tweeted_at, format: :tweet)
    via
    = status.source.html_safe
    - if status.is_reply?
      = link_to "to @#{status.in_reply_to_screen_name}", status.in_reply_to_url

app/views/statuses/_statuses.haml
%ul
  - @statuses.each do |status|
    %li{ id: status.html_id }= render status

app/views/statuses/index.html.haml
- if action_name == "search"
  - content_for :title, "Searching for ‘#{params[:q]}’"
- elsif @date
  - content_for :title, "Tweets from #{l(@date, format: :month_and_year)}"
- elsif @user.present?
  - content_for :title, "@#{@user.name}'s tweets"
%nav#navigation
  .wrapper
    - if @oldest.present? && @newest.present?
      .timeline
        %form
          %select{ name: "month" }
            %option Recent
            - tweet_dates(@oldest, @newest).each do |year, dates|
              %optgroup{ label: year }
                - dates.each do |date|
                  %option{ value: l(date, format: :internal), selected: date == @date }= date.strftime("%B")
          %input{type: 'submit'}
    - if @statuses.any? || is_search?
      .search
        = form_tag search_path, method: :get do
          = search_field_tag :search, params[:q], results: '5', name: 'q'
          = submit_tag "Search"

%header

  - cache @user do
    .profile
      = link_to @user.twitter_url do
        %h1= @user.display_name
        %p= "@#{@user.name}"

%section{:role => "main"}

  - if @statuses.any?
    - if is_search?
      %h2
        = link_to "← Home", root_path
        |
        = "Results for ‘#{params[:q]}’"
      = render "statuses"
    - else
      - cache @cache_name do
        = render "statuses"
  - else
    %h2
      - if is_search?
        = link_to "← Home", root_path
        |
        = "No results found for ‘#{params[:q]}’"
      - else
        No Tweets have been imported yet.

%footer
  .footer-icons &#9670; &#9670; &#9670;

  - if @oldest.present? && @newest.present?
    %noscript
      %nav.timeline
        = link_to "Recent", root_path
        - tweet_dates(@oldest, @newest).each do |year, dates|
          .year
            %h3= year
            - dates.each do |date|
              = link_to_unless (date == @date), date.strftime("%B"), statuses_for_month_path(month: l(date, format: :internal))

app/views/statuses/unauthenticated.html.haml
#login
  - if current_user
    You are
    = '@' + current_user.name + '.'
    <br/>
    = link_to "Your tweets", statuses_path(limit: 100)
  - else
    Hey there.<br/>
    = link_to "Sign in via Twitter", "/auth/twitter"